allowBuilds:
  '@owservable/folders': true
  es5-ext: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - request@2.88.3
  - tough-cookie@4.1.3
  - form-data@2.5.4 || 2.5.6
  - qs@6.14.1
  - uuid@11.1.1
  - '@owservable/folders@2.2.2'

overrides:
  'mem@<4.0.0': '>=4.0.0'
  'yargs-parser@>=6.0.0 <13.1.2': '>=13.1.2'
  'nanoid@>=3.0.0 <3.1.31': '>=3.1.31'
  'semver@<5.7.2': '>=5.7.2'
  '@babel/traverse@<7.23.2': '>=7.23.2'
  'json5@>=2.0.0 <2.2.2': '>=2.2.2'
  'tough-cookie@<4.1.3': '>=4.1.3'
  'unzip-stream@<0.3.2': '>=0.3.2'
  'cross-spawn@<6.0.6': '>=6.0.6'
  '@babel/helpers@<7.26.10': '>=7.26.10'
  'tar-fs@<1.16.5': '>=1.16.5'
  'brace-expansion@>=1.0.0 <=1.1.11': '>=1.1.12'
  'brace-expansion@>=2.0.0 <=2.0.1': '>=2.0.2'
  'form-data@<2.5.4': '>=2.5.4'
  'tar-fs@>=3.0.0 <3.1.1': '>=3.1.1'
  'js-yaml@<3.14.2': '>=3.14.2'
  'glob@>=10.2.0 <10.5.0': '>=10.5.0'
  'qs@<6.14.1': '>=6.14.1'
  'lodash@>=4.0.0 <=4.17.22': '>=4.17.23'
  'diff@<4.0.4': '>=4.0.4'
  '@isaacs/brace-expansion@<=5.0.0': '>=5.0.1'
  'qs@>=6.7.0 <=6.14.1': '>=6.14.2'
  'test-exclude': '^7.0.1'
  'minimatch@<3.1.3': '>=3.1.3'
  'minimatch@>=10.0.0 <10.2.1': '>=10.2.1'
  'minimatch@>=10.0.0 <10.2.3': '>=10.2.3'
  'minimatch@<3.1.4': '>=3.1.4'
  'ajv@<6.14.0': '>=6.14.0'
  'brace-expansion@>=2.0.0 <2.0.3': '>=2.0.3'
  'lodash@>=4.0.0 <=4.17.23': '>=4.18.0'
  'lodash@<=4.17.23': '>=4.18.0'
  'uuid@<14.0.0': '>=14.0.0'
