import PostgresBackend from './postgres.backend';
import PostgresConnector, { type PostgresConnectorOptionsType } from './postgres.connector';
import PostgresListener, { type PostgresNotificationType } from './postgres.listener';
import PostgresTablesEntitiesMap from './tables.entities.map';
import PostgresLiveUpdates, { PostgresLiveUpdatesRegistry } from './decorators/live.updates';
import PostgresObservableTable from './functions/observable.table';
import PostgresObservableTablesMap from './functions/observable.tables.map';
import installPostgresTriggers from './functions/install.triggers';
import processPostgresEntities from './functions/process.entities';
export { PostgresBackend, PostgresConnector, PostgresListener, PostgresTablesEntitiesMap, PostgresLiveUpdates, PostgresLiveUpdatesRegistry, PostgresObservableTable, PostgresObservableTablesMap, installPostgresTriggers, processPostgresEntities };
export type { PostgresConnectorOptionsType, PostgresNotificationType };
declare const OwservablePostgres: {};
export default OwservablePostgres;
